name: main branch pr

on:
  push:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  terraform_dev:
    uses: ./.github/workflows/terraform-environment.yml
    secrets: inherit
    with:
      environment: "dev"

  terraform_qa:
    uses: ./.github/workflows/terraform-environment.yml
    secrets: inherit
    with:
      environment: "qa"
