name: tear-down-feature-environment

on:
  workflow_call:

jobs:
  terraform-environment:
    runs-on: [ubuntu-latest]
    env:
      AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
      AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}

    steps:
      - name: Get feature name
        id: get_branch_name
        run: |
          brachName=$GITHUB_BASE_REF
          parts=(${brachName//\// })
          feature=${parts[-1]}
          echo "feature=$feature" >> $GITHUB_OUTPUT

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform init
        run: |
          terraform init

      - name: Change terraform workspace for environment
        run: |
          terraform workspace select ${{steps.get_branch_name.feature}} || terraform workspace new ${{steps.get_branch_name.feature}}

      - name: Terraform destroy
        run: |
          terraform destroy
