name: terraform-environment.yml

on:
  workflow_call:
    inputs:
      environment:
        type: string
        description: values should be prod, qa, dev or adhoc environment name for special feature development, such as integration-xyz

jobs:
  validate-environment:
    runs-on: [ubuntu-latest]
    env:
      AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
      AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Environment
        working-directory: ./infrastructure
        run: |
          terraform init
          terraform workspace select -or-create=true ${{inputs.environment}}
          terraform refresh
          terraform validate
          terraform plan
